[IG]
ig = fsh-generated/resources/ImplementationGuide-mii-ig-bildgebung.json
# Template: fhir2.base.template (fhir.base.template wegen gemeldeter Security-Issues nicht genutzt).
template = fhir2.base.template#current
