@startuml
class ImagingStudy #LightCyan {
  + Prozedur: Reference(Procedure) [0..1]
  + Identifier der ImagingStudy: Identifier[0..*]
  + Status: Coding [1..1]
  + Studien-Beschreibung: string [0..1]
  + Anzahl an enthaltenen SOP Instanzen: unsignedInt [0..1]
  + Anzahl an enhaltenen Serien: unsignedInt [0..1]
  + Beginn: dateTime [0..1]
  + Indikation: Reference(Condition|Observation) [0..1]
  + Modalitäten: Coding[0..*]
  + Quelle zum PACS Bild: Reference(Endpoint)[0..*]
  + Anfordernde Maßnahme: Reference(ServiceRequest)[0..*]
  + Übergeordnete Maßnahme: Reference(Procedure) [0..1]
  + Bildgebungsgrund: Reference(Condition|Observation)[0..*]
  + Fall-Referenz: Reference(Encounter) [0..1]
  + Personen-Identifikation: Reference(Patient) [1..1]
  + DICOM-Serien: DICOM-Serie[0..*]
}

class DICOMSerie #LightBlue {
  + Serien-UID: id [1..1]
  + Serien-Nummer: unsignedInt [0..1]
  + Modalität: Coding [1..1]
  + Serienbeschreibung: string [0..1]
  + Anzahl an in Serie enthaltenen Instanzen: unsignedInt [0..1]
  + Untersuchte Körperregion: Coding [0..1]
  + Körperseite: Coding [0..1]
  + Beginn: dateTime [0..1]
  + DICOM-Instanzen: Instance[0..*]
  + Hersteller: CodeableConcept [0..1]
  + Modell: string [0..1]
  + Kontrastmittelgabe: boolean [0..1]
  + Kontrastmitteldetails: Reference(MII_PR_Medikation_MedicationStatement) [0..*]
}

class DICOMInstanz #LightGreen {
  + SOP-Instanz UID: id [1..1]
  + SOP-Klasse: Coding [1..1]
  + Instanz-Nummer: unsignedInt [0..1]
  + Beschreibung der SOP Instanz: string [0..1]
}

class ModalitätMR #LightYellow {
  + Scanning Sequenz: CodeableConcept [1..*]
  + Scanning Sequenz Untervariante: CodeableConcept [1..1]
  + Magnetische Feldstärke: Quantity[T] [1..1]
}

class ModalitätCT #LightYellow {
  + CTDIvolume: Quantity[mGy] [0..1]
  + Maximale Röntgenröhrenspannung: Quantity[kV] [0..1]
  + Expositionszeit: Quantity[ms] [0..1]
  + Exposition: Quantity[mAs] [0..1]
  + Röntgenröhrenstrom: Quantity[mA] [0..1]
} 

class ModalitätDX #LightYellow {
  + Maximale Röntgenröhrenspannung: Quantity[kV] [0..1]
  + Expositionszeit: Quantity[ms] [0..1]
  + Exposition: Quantity[mAs] [0..1]
  + Röntgenröhrenstrom: Quantity[mA] [0..1]
} 

class ModalitätCR #LightYellow {
  + Maximale Röntgenröhrenspannung: Quantity[kV] [0..1]
  + Expositionszeit: Quantity[ms] [0..1]
  + Exposition: Quantity[mAs] [0..1]
  + Röntgenröhrenstrom: Quantity[mA] [0..1]
} 

class ModalitätMG #LightYellow {
  + Maximale Röntgenröhrenspannung: Quantity[kV] [0..1]
  + Expositionszeit: Quantity[ms] [0..1]
  + Exposition: Quantity[mAs] [0..1]
  + Röntgenröhrenstrom: Quantity[mA] [0..1]
} 

class ModalitätNM #LightYellow {
  + Radiopharmakon: string [0..1]
  + Applikationsstartzeit: dateTime [0..1]
  + Applikationsstopzeit: dateTime [0..1]
  + Gesamte Radionukliddosis: Quantity[MBq] [0..1]
  + Halbwertszeit: Quantity[s] [0..1]
} 

class ModalitätPET #LightYellow {
  + Radiopharmakon: string [0..1]
  + Applikationsstartzeit: dateTime [0..1]
  + Applikationsstopzeit: dateTime [0..1]
  + Gesamte Radionukliddosis: Quantity[Bq] [0..1]
  + Halbwertszeit: Quantity[s] [0..1]
} 

ImagingStudy "1..N" -- "0..*" DICOMSerie
DICOMSerie "1..N" -- "0..*" DICOMInstanz
DICOMSerie "0..1" -- "1..1" ModalitätMR
DICOMSerie "0..1" -- "1..1" ModalitätCT
DICOMSerie "0..1" -- "1..1" ModalitätDX
DICOMSerie "0..1" -- "1..1" ModalitätCR
DICOMSerie "0..1" -- "1..1" ModalitätMG
DICOMSerie "0..1" -- "1..1" ModalitätNM
DICOMSerie "0..1" -- "1..1" ModalitätPET
@enduml
