@startuml
class ImagingStudy #LightCyan {
  + Identifier der ImagingStudy: Identifier[*]
  + Status: Coding
  + Modalitäten: Coding[*]
  + Personen-Identifikation: Reference(Patient)
  + Fall-Referenz: Reference(Encounter)
  + Beginn: dateTime
  + Anfordernde Maßnahme: Reference(ServiceRequest)[*]
  + Quelle zum PACS Bild: Reference(Endpoint)[*]
  + Anzahl an enhaltenen Serien: unsignedInt
  + Anzahl an enthaltenen SOP Instanzen: unsignedInt
  + Übergeordnete Maßnahme: Reference(Procedure)
  + Bildgebungsgrund: Reference(Condition|Observation|Media|DiagnosticReport|DocumentReference)[*]
  + Studien-Beschreibung: string
  + DICOM-Serien: DICOM-Serie[*]
}
note left: Work in Progress

class DICOMSerie #LightBlue {
  + Serien-UID: id
  + Serien-Nummer: unsignedInt
  + Modalität: Coding
  + Serienbeschreibung: string
  + Anzahl an in Serie enthaltenen Instanzen: unsignedInt
  + Untersuchte Körperregion: Coding
  + Körperseite: Coding
  + Beginn: dateTime
  + DICOM-Instanzen: Instance[0..*]
  + Bilderzeugende Einrichtung: Reference[0..*]
}

class DICOMInstanz #LightGreen {
  + SOP-Instanz UID: id [1..1]
  + SOP-Klasse: Coding [1..1]
  + Instanz-Nummer: unsignedInt [0..1]
  + Beschreibung der SOP Instanz: string [0..1]
}

class BilderzeugendeEinrichtung #LightGreen {
  + Akteur: Reference(PractitionerRole|Organization|CareTeam|Device) [1..1]
  + Funktion: string [0..1]
}

ImagingStudy "1..N" -- "0..*" DICOMSerie
DICOMSerie "1..N" -- "0..*" DICOMInstanz
DICOMSerie "1..N" -- "0..*" BilderzeugendeEinrichtung 
@enduml
