@startuml
skinparam Linetype ortho
skinparam Nodesep 150
skinparam Ranksep 80
skinparam legendBackgroundColor #white

class Körperstruktur <<BodyStructure>> {
  + Morphologie: CodeableConcept [0..1]
  + Lokalisation: CodeableConcept [0..1]
  + nähere Lokalisation: CodeableConcept [0..*]
  + {field} Personen-Identifikation: Reference(Patient) [1..1]
}

package "Befund" {
  class Befundbericht <<DiagnosticReport>> #LightCyan {
  + {field} Anfordende Maßnahme: Reference(ServiceRequest) [0..*]
  + Status: Coding [1..1]
  + Kategorie: CodeableConcept [1..*]
  + Code: Coding [1..1]
  + {field} Personen-Identifikation: Reference(Patient) [1..1]
  + {field} Versorgungsstellenkontakt: Reference(Encounter) [0..1]
  + Klinisch relevante Zeit: dateTime [0..1]
  + Klinisch relevante Periode: period [0..1]
  + Zeit der Erstellung: issued [0..1]
  + {field} Beobachtung: Reference(Observation) [0..*]
  + {field} Studienbezug: Reference(ImagingStudy) [1..*]
  + Interpretation der Beobachtung: markdown [0..1]
  + strukturierte Interpretation: CodeableConcept [0..*]
  + {field} Zusatzinformation: Reference(DiagnosticReport|Procedure) [0..1]
  + {field} Dokumentenanhang: Attachment [0..*]
  }
  
  class Empfehlung <<CarePlan>> {
  + Status: Coding [1..1]
  + Art der Empfehlung: Coding [1..1]
  + Freitextempfehlung: String [0..1]
  + {field} Personen-Identifikation: Reference(Patient) [1..1]
  + {field} Zusatzinformation: Reference(DiagnosticReport) [0..*] 
  }

  package "Generisch" {
    class GenerischeBeobachtung <<Observation>> {
    + {field} Extension: Bildnummer: DICOM Instance UID (Series) [0..1]
    + {field} Extension: Schichtposition: DICOM Instance UID (SOP Instance) [0..1]
    + {field} Extension: Erweiterte Körperstruktur: Reference(BodyStructure) [0..1]
    + {field} Teil einer Befundungsprozedur: Reference(Procedure) [0..*]
    + Status: Coding [1..1]
    + Beobachtungsklassifizierung: CodeableConcept [0..*]
    + Beobachtungstyp: CodeableConcept [1..1]
    + {field} Personen-Identifikation: Reference(Patient) [1..1]
    + Beobachtungszeitpunkt: issued [0..1]
    + Beschreibung: value[x] [0..1]
    + {field} Körperregion(bodySite): CodeableConcept [0..1]
    + {field} weitere Beobachtung: Reference(Observation) [0..*]
    + {field} Studienbezug: Reference(ImagingStudy) [0..*]
    + erweiterte Beschreibung: component [0..*]
    }
  }

  package "Semistruktur"{
    class SemistrukturiertesBefunddokument <<Composition>>{
    + Status: Coding [1..1]
    + Typ: CodeableConcept [1..1]
    + Datum und Uhrzeit der Bearbeitung: DateTime [1..1]
    + {field} Autor: Reference(Practitioner) [1..*]
    + Titel: String [1..1]
    + Befundabschnitt: BackboneElement [1..*]
    }

    class Befundabschnitt <<Composition.section>> {
    + Titel des Abschnitts: String [0..1]
    + Art des Abschnitts: CodeableConcept [0..1]
    + {field} Autor des Abschnitt: Reference(Practitioner) [0..*]
    + Text: Narrative [0..1]
    + {field} Eintrag: Reference(Observation|DiagnosticReport) [1..*]
    + Unterabschnitt: Composition.section.section [0..*]
    }
  }
}

Befundbericht "1..1" -u- "0..*" Befundbericht: DR.supportingInfo (R5!)
Befundbericht "1..1" -- "0..*" GenerischeBeobachtung: DR.result

Empfehlung "0..*" -- "0..*" Befundbericht: CP.supportingInfo

GenerischeBeobachtung "1..1" -u- "0..*" GenerischeBeobachtung: Obs.hasMember
GenerischeBeobachtung "0..*" -- "0..1" Körperstruktur: Obs.bodyStructure (R5!)

SemistrukturiertesBefunddokument "1..1" -- "1..*" Befundabschnitt: Co.section

Befundabschnitt "1..1" -- "1..1" Befundbericht: Co.section.entry
Befundabschnitt "1..1" -u- "0..*" Befundabschnitt: Co.section.section
Befundabschnitt "0..1" -- "0..*" GenerischeBeobachtung: Co.section.entry
@enduml
