@startuml
skinparam Linetype ortho
skinparam Nodesep 380
skinparam Ranksep 200
skinparam legendBackgroundColor #white

class Studie <<ImagingStudy>> #LightCyan {}

class Anforderung <<ServiceRequest>> {}

class Körperstruktur <<BodyStructure>> {}

package "Befund" {
  class Befundbericht <<DiagnosticReport>> #LightCyan {}
  
  class Empfehlung <<CarePlan>> {}

  class GenerischeBeobachtung <<Observation>> {}

  class RadiologischeMessung <<Observation>> {}

  class SemistrukturiertesBefunddokument <<Composition>>{}
}

Befundbericht "0..1" -- "0..*" Anforderung: DR.basedOn
Befundbericht "1..1" -- "0..*" GenerischeBeobachtung: DR.result
Befundbericht "1..1" -- "0..*" RadiologischeMessung: DR.result
Befundbericht "0..*" -l- "0..*" Studie: DR.imagingStudy
Befundbericht "1..1" -u- "0..*" Befundbericht

Empfehlung "0..*" -- "0..*" Befundbericht: CP.supportingInfo

GenerischeBeobachtung "0..*" -- "0..1" Körperstruktur: Obs.bodyStructure (R5!)
GenerischeBeobachtung "1..1" -u- "0..*" GenerischeBeobachtung: Obs.hasMember
GenerischeBeobachtung "0..*" -- "0..*" Studie: Obs.derivedFrom
RadiologischeMessung "0..*" -- "0..1" Körperstruktur: Obs.bodyStructure (R5!)
RadiologischeMessung "1..1" -u- "0..*" RadiologischeMessung: Obs.hasMember
RadiologischeMessung "0..*" -- "0..*" Studie: Obs.derivedFrom

Studie "0..*" -- "0..*" Anforderung: ISt.basedOn

Anforderung "0..*" -- "0..*" Studie: SR.supportingInfo
Anforderung "0..1" -- "0..*" Befundbericht: SR.supportingInfo

SemistrukturiertesBefunddokument "1..1" -- "1..1" Befundbericht: Co.section.entry
SemistrukturiertesBefunddokument "0..1" -- "0..*" GenerischeBeobachtung : Co.section.entry
@enduml
