@startuml
skinparam Linetype ortho
skinparam Nodesep 150
skinparam Ranksep 80


class Studie <<ImagingStudy>> #LightCyan {
  + {field} Prozedur: Reference (Procedure) [0..1]
  + Identifier der ImagingStudy: Identifier[0..*]
  + Status: Coding [1..1]
  + Studien-Beschreibung: string [0..1]
  + Anzahl an enthaltenen SOP Instanzen: unsignedInt [0..1]
  + Anzahl an enhaltenen Serien: unsignedInt [0..1]
  + Beginn: dateTime [0..1]
  + {field} Indikation: Reference(Condition|Observation) [0..1]
  + Modalitäten: Coding[0..*]
  + {field} Quelle zum PACS Bild: Reference(Endpoint)[0..*]
  + {field} Anfordernde Maßnahme: Reference(ServiceRequest)[0..*]
  + {field} Übergeordnete Maßnahme: Reference(Procedure) [0..1]
  + {field} Bildgebungsgrund: Reference(Condition|Observation)[0..*]
  + {field} Fall-Referenz: Reference(Encounter) [0..1]
  + {field} Personen-Identifikation: Reference(Patient) [1..1]
  + DICOM-Serien: DICOM-Serie[0..*]
}

package "DICOM-Header" {
  class DICOMSerie {
  + Serien-UID: id [1..1]
  + Serien-Nummer: unsignedInt [0..1]
  + Modalität: Coding [1..1]
  + Serienbeschreibung: string [0..1]
  + Anzahl an in Serie enthaltenen Instanzen: unsignedInt [0..1]
  + Untersuchte Körperregion: Coding [0..1]
  + Körperseite: Coding [0..1]
  + Beginn: dateTime [0..1]
  + DICOM-Instanzen: Instance[0..*]
  + Hersteller: CodeableConcept [0..1]
  + Modell: string [0..1]
  + Kontrastmittelgabe: boolean [0..1]
  + {field} Kontrastmitteldetails: Reference(MII_PR_Medikation_MedicationStatement) [0..*]
}

  class DICOMInstanz {
  + SOP-Instanz UID: id [1..1]
  + SOP-Klasse: Coding [1..1]
  + Instanz-Nummer: unsignedInt [0..1]
  + Beschreibung der SOP Instanz: string [0..1]
}

  class ModalitätMR #LightYellow {
  + Scanning Sequenz: CodeableConcept [1..*]
  + Scanning Sequenz Untervariante: CodeableConcept [1..1]
  + Magnetische Feldstärke: Quantity[T] [1..1]
}

  class ModalitätCT #LightYellow {
  + CTDIvolume: Quantity[mGy] [0..1]
  + Maximale Röntgenröhrenspannung: Quantity[kV] [0..1]
  + Expositionszeit: Quantity[ms] [0..1]
  + Exposition: Quantity[mAs] [0..1]
  + Röntgenröhrenstrom: Quantity[mA] [0..1]
} 

  class ModalitätDX #LightYellow {
  + Maximale Röntgenröhrenspannung: Quantity[kV] [0..1]
  + Expositionszeit: Quantity[ms] [0..1]
  + Exposition: Quantity[mAs] [0..1]
  + Röntgenröhrenstrom: Quantity[mA] [0..1]
} 

  class ModalitätCR #LightYellow {
  + Maximale Röntgenröhrenspannung: Quantity[kV] [0..1]
  + Expositionszeit: Quantity[ms] [0..1]
  + Exposition: Quantity[mAs] [0..1]
  + Röntgenröhrenstrom: Quantity[mA] [0..1]
} 

  class ModalitätMG #LightYellow {
  + Maximale Röntgenröhrenspannung: Quantity[kV] [0..1]
  + Expositionszeit: Quantity[ms] [0..1]
  + Exposition: Quantity[mAs] [0..1]
  + Röntgenröhrenstrom: Quantity[mA] [0..1]
} 

  class ModalitätNM #LightYellow {
  + Radiopharmakon: string [0..1]
  + Applikationsstartzeit: dateTime [0..1]
  + Applikationsstopzeit: dateTime [0..1]
  + Reskalierungstyp: String [0..1]
  + Gesamte Radionukliddosis: Quantity[MBq] [0..1]
  + Halbwertszeit: Quantity[s] [0..1]
} 

  class ModalitätPET #LightYellow {
  + Radiopharmakon: string [0..1]
  + Applikationsstartzeit: dateTime [0..1]
  + Applikationsstopzeit: dateTime [0..1]
  + Reskalierungstyp: String [0..1]
  + Gesamte Radionukliddosis: Quantity[Bq] [0..1]
  + Halbwertszeit: Quantity[s] [0..1]
}
}

class Anforderung <<ServiceRequest>> {
}

package "Befund" {
  class Befundbericht <<DiagnosticReport>> #LightCyan {
  + {field} Basierend auf: Reference(ServiceRequest) [0..*]
  + Status: Coding [1..1]
  + {field} Personen-Identifizierung: Reference (Patient) [1..1]
  + {field} Fall-Referenz: Reference (Encounter) [0..1]
  + Klinisch relevante Zeit: dateTime [0..1]
  + Klinisch relevante Periode: period [0..1]
  + Erstellungszeit: instant [0..1]
  + {field} Ergebnis: Reference(Observation) [1..1]
  + {field} Studie: Reference(ImagingStudy) [1..1]
  + {field} Zusatzinformation: Reference(DiagnosticReport) [0..1]
  + Ergebisinterpretation: markdown [0..1]
  + Codierte Ergebnisinterpretation: CodeableConcept [0..1]
  + {field} Dokument: Attachment [0..*]
}
  
  class Empfehlung <<CarePlan>> {

}

  package "Generisch" {
  class GenerischeBeobachtung <<Observation>> {
  + {field} Extension: Bildnummer: DICOM Instance UID (Series)
  + {field} Extension: Schichtposition: DICOM Instance UID (SOP Instance)
  + Status: Coding [1..1]
  + Beobachtungstyp: CodeableConcept [1..1]
  + Beobachtungszeitpunkt: instant [0..1]
  + Beschreibung: value[x] [0..1]
  + {field} Körperstelle (bodySite): CodeableConcept [0..1]
  + {field} Studienbezug: Reference(ImagingStudy) [0..*]
  + {field} weitere Beobachtung: Reference(Observation) [0..*]
  + erweiterte Beschreibung: component [0..*]
}

  class Körperstruktur <<BodyStructure>> {
  + Morphologie: CodeableConcept [0..1]
  + Lokalisation: CodeableConcept [0..1]
  + nähere Lokalisation: CodeableConcept [0..1]
}

}

  package "Semistruktur"{
  class SemistrukturiertesBefunddokument <<Composition>>{
 + Angaben zum Autor
 + Unterzeichner
 + Datum der Unterschrift 
}

  class Befundabschnitt <<Composition.section>> {
 + {field} Titel (Fragestellung,Beschreibung, Beurteilung, Empfehlung, ...)
 + Code
 + Text
}
}

}

package "Basismodule" {
  class "Patient:in" <<from Person>> #Lightgreen {
}

  class Versorgungsstellenkontakt? <<from Fall>> #Lightgreen {
}

  class Vorbefund <<Condition From Diagnose>> #Lightgreen {
}
  
  class Bildgebung <<from Procedure>> #Lightgreen {
}

  class Kontrastmittelgabe_Medikationsgabe <<MedicationAdministration derived from Medikation>> #Lightgreen {
}


    class Befundungsprozedur <<from Procedure>> #Lightgreen {
}
}


DICOMSerie "1..N" -l- "0..*" DICOMInstanz
DICOMSerie "0..1" -u- "1..1" ModalitätMR
DICOMSerie "0..1" -u- "1..1" ModalitätCT
DICOMSerie "0..1" -u- "1..1" ModalitätDX
DICOMSerie "0..1" -d- "1..1" ModalitätCR
DICOMSerie "0..1" -d- "1..1" ModalitätMG
DICOMSerie "0..1" -d- "1..1" ModalitätNM
DICOMSerie "0..1" -r- "1..1" ModalitätPET

Bildgebung "0..*" --> "0..*" Anforderung : basedOn
Bildgebung -[hidden]u- Befundungsprozedur

Kontrastmittelgabe_Medikationsgabe "0..*" -r-> "1..*" Bildgebung : partOf

Befundbericht --> Anforderung : basedOn
Befundbericht "0..*" --> "0..*" Studie : imagingStudy
Befundbericht ..> Befundbericht : supportingInfo(R5!)
Befundbericht "0..*" --> "1..1" "Versorgungsstellenkontakt?" : encounter
Befundbericht --> Befundungsprozedur
Befundbericht "0..*" --> "1..1" "Patient:in" : subject
Befundbericht "1..1" --> "0..*" GenerischeBeobachtung: result

Empfehlung ..> Befundbericht : supportingInfo 

GenerischeBeobachtung --> Studie : derivedFrom
GenerischeBeobachtung --> GenerischeBeobachtung: hasMember
GenerischeBeobachtung --> "0..1" Körperstruktur: bodyStructure/focus(versioned)
GenerischeBeobachtung --> Befundungsprozedur: partOf

Studie "0..*" --> "1..1" "Versorgungsstellenkontakt?" : encounter
Studie "0..*" --> "1..1" "Patient:in" : subject
Studie --> Anforderung : basedOn
Studie -up-> Bildgebung : procedureReference
Studie "1..N" -l- "0..*" DICOMSerie

Anforderung "0..*" --> "0..*" Vorbefund : reasonRef
Anforderung "0..*" ..> "0..*" Studie : supportingInfo
Anforderung "0..*" ..> "0..*" Befundbericht : supportingInfo
Anforderung --> "0..*" Befundungsprozedur: basedOn

SemistrukturiertesBefunddokument --> "0..1" Befundbericht
SemistrukturiertesBefunddokument --> "0..*" Befundabschnitt
SemistrukturiertesBefunddokument --> "1..1" "Patient:in"

Befundabschnitt --> Befundabschnitt
Befundabschnitt --> "0..*" GenerischeBeobachtung : entry
@enduml