//bildgebungsgrund
//modality
//numberOfSeries
//numberOfInstances
//ProcRef
//reasRef
//description
//series.modalityCT
//series.modalityMG_CR
//series.modalityMR
//series.modalityPT
//series.kontrastmittel
//series.gerät
//series.number
//series.description
//series.numInstance
//series.laterality
//series.started
//instance.imagingInstance
//instance.number
