Logical: MII_LM_Bildgebung
Parent: Element
Id: mii-lm-bildgebung
Title: "MII LM Bildgebung"
Description: "MII LogicalModel Modul Bildgebung"
* insert Translation(^name, en-US, MII_LM_Bildgebung)
* insert Translation(^title, en-US, MII LM Bildgebung)
* insert Translation(^description, en-US, MII LogicalModel Module Bildgebung)
* insert Publisher
* insert PR_CS_VS_Version
* insert KDS_Copyright
* ^date = "2024-07-03"
* ^url = "https://www.medizininformatik-initiative.de/fhir/ext/modul-Bildgebung/StructureDefinition/LogicalModel/Bildgebung"
* . ^short = "Das Erweiterungsmodul Bildgebung enthält Datenelemente zur Dokumentation Bildgebungsstudien und radiologischen Befundberichten"

* Empfehlung 0..* BackboneElement "Empfehlung" "Therapieempfehlungen aus vorherigen Behandlungen"
  * Status 1..1 http://hl7.org/fhir/StructureDefinition/Coding "Status" "Status der Behandlungsempfehlung"
  * ArtEmpfehlung 1..1 http://hl7.org/fhir/StructureDefinition/Coding "Art der Empfehlung" "Beschreibt die Art der Empfehlung."
  * FreitextEmpfehlung 0..1 http://hl7.org/fhir/StructureDefinition/string "Freitextempfehlung" ""
  * Zusatzinformation 0..1 Reference(DiagnosticReport) "Zusatzinformation" "Zusatzinformation für einen Befundbericht"
* Befundbericht 1..1 BackboneElement "Befundbericht" ""
  * AnforderndeMaßnahme 0..* Reference(ServiceRequest) "Anfordernde Maßnahme" "Basiert auf einer ServiceRequest-Anfrage."
  * Status 1..1 http://hl7.org/fhir/StructureDefinition/Coding "Status" "Status des Befundberichts."
  * Person 0..1 Reference(Patient) "Personen-Identifikation" "Die Person, für die der Befundbericht erstellt wurde."
  * Fall 1..1 Reference(Encounter) "Fall-Referenz" "Referenz über Fall auf den Versorgungsstellenkontakt."
  * Zeitpunkt 0..1 http://hl7.org/fhir/StructureDefinition/dateTime "Klinisch relevanter Zeitpunkt" "Klinisch relevanter Zeitpunkt, auf den sich der Bericht bezieht."
  * Periode 0..1 http://hl7.org/fhir/StructureDefinition/Period "Klinisch relevante Periode" "Klinisch relevante Periode, auf die sich der Bericht bezieht."
  * ZeitpunktErstellung 0..1 http://hl7.org/fhir/StructureDefinition/dateTime "Zeitpunkt der Erstellung" "Zeitpunkt der Erstellung des Berichts."
  * Beobachtung 0..* Reference(Observation) "Beobachtung" "Referenz auf die generische Beobachtung."
  * Studienbezug 1..* Reference(ImagingStudy) "Studienbezug" "Bezug auf die zugehörige(n) Bildgebungsstudie(n)."
  * InterpretationBeobachtung 0..1 http://hl7.org/fhir/StructureDefinition/markdown "Interpretation" "Freitextinterpretation der Beobachtung."
  * StrukturierteInterpretation 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "Strukturierte Interpretation" "Strukturierte Interpretation der Beobachtung."
  * Zusatzinformation 0..1 Reference(DiagnosticReport or Procedure) "Zusatzinformation" "Referenz auf weitere Befundberichte zum Patienten."
  * Dokumentenanhang 0..* http://hl7.org/fhir/StructureDefinition/Attachment "Dokumentenanhang" "Anhang der Dokumente und Bilder."
* SemistrukturiertesBefunddokument 1..1 BackboneElement "Semistrukturiertes Befunddokument" "Abbildung des Befunds über generische Composition."
  * DatumUhrzeit 1..1 http://hl7.org/fhir/StructureDefinition/dateTime "Datum und Uhrzeit der Bearbeitung" ""
  * Autor 1..* Reference(Practitioner) "Autor" "Referenz auf den Autor der Beschreibung."
  * Befundbericht 1..1 Reference(DiagnosticReport) "Befundbericht" "Referenz auf den zugeordneten Befundbericht."
  * Befundabschnitt 0..* BackboneElement "Befundabschnitt" "Befundabschnitt des semistrukturierten Befunddokuments."
    * Titel 0..1 http://hl7.org/fhir/StructureDefinition/string "Titel" "Titel des Befundabschnitts."
    * Art 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "Art" "Art des Befundabschnitts."
    * Text 0..1 http://hl7.org/fhir/StructureDefinition/Narrative "Text" "Textueller Inhalt des Befundabschnitts."
    * Eintrag 0..* Reference(Observation) "Eintrag" "Referenz auf eine Observation, die zum Eintrag des Befundabschnitts gehört."
    * Unterabschnitt 0..1 BackboneElement "Unterabschnitt" "Referenz auf einen weiteren Unterabschnitt."
* GenerischeBeobachtung 0..* BackboneElement "Befundabschnitt" "Befundabschnitt des semistrukturierten Befunddokuments."
  * TeilEinerBefundungsprozedur 0..* Reference(Procedure) "Teil einer Befundungsprozedur" ""
  * Beobachtungstyp 1..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "Beobachtungstyp" "Typ der Beobachtung."
  * Status 1..1 http://hl7.org/fhir/StructureDefinition/Coding "Status" "Status der Beobachtung."
  * Beobachtungszeitpunkt 0..1 http://hl7.org/fhir/StructureDefinition/dateTime "Beobachtungszeitpunkt" "Zeitpunkt an dem die Beobachtung gemacht wird."
  * Beschreibung 0..1 BackboneElement "Beschreibung" "Detaillierte Beschreibung der Beobachtung mit value[x]."
  * Körperregion 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "Körperregion" "Codierte Körperregion der Beobachtung"
  * Studienbezug 0..* Reference(ImagingStudy) "Studienbezug" "Bezug auf die zugehörige(n) Bildgebungsstudie(n)."
  * WeitereBeobachtung 0..* Reference(Observation) "Weitere Beobachtung(en)" "Weitere Beobachtung(en) als Referenz auf weitere Observation(s)."
  * ErweiterteBeschreibung 0..* BackboneElement "Erweiterte Beschreibung" "Kann mehrere Beschreibungen strukturiert abbilden."
  * Bildnummer 0..1 http://hl7.org/fhir/StructureDefinition/string "Bildnummer" "DICOM Series UID der zugehörigen Serie."
  * Schichtposition 0..1 http://hl7.org/fhir/StructureDefinition/string "Schichtposition" "DICOM Instance UID der zugehörigen SOP Instance."
  * ErweiterteKörperstruktur 0..1 Reference(BodyStructure) "Erweiterte Körperstruktur" "Backport der R5 Referenz auf das BodyStructure-Profil."
* BodyStructure 0..1 BackboneElement "Körperstruktur" "Körperstruktur"
  * Morphologie 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "Morphologie" "Morphologie"
  * Lokalisation 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "Lokalisation" "Lokalisation"
  * nähereLokalisation 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "mähere Lokalisation" "nähere Lokalisation"
* Anforderung 0..1 BackboneElement "Anforderung" "Anfoderung der jeweiligen Bildgebungsmaßnahme"
  * ArtAnfrage 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "Art der Anfrage" "Art der Anfrage"
  * Patientenbezug 1..1 Reference(Patient) "Patientenbezug" "Bezug zu dem Patienten, für den die Anfoderung besteht"
  * Zusatzinformation 0..1 Reference(DiagnosticReport) "Zusatzinformation" "Zusatzinformation zur jeweiligen Anfoderung"
* Studie 0..* BackboneElement "Studie" "Bildgebungsstudie"
  * Status 1..1 http://hl7.org/fhir/StructureDefinition/Coding "Status" "Status der Bildgebungsstudie- Info darüber, ob die Studie gültig, ungültig, zurückgezogen, etc. ist."
  * Modalitäten 0..* http://hl7.org/fhir/StructureDefinition/Coding "Modalitäten" "Set/Liste aller verschiedenen Modalitäten, die in dieser DICOM-Studie enthalten sind."
  * Person 1..1 Reference(Patient) "Person" "Person, auf die sich die Bildgebungsstudie bezieht"
  * Fall 0..1 Reference(Encounter) "Fall-Referenz" "Referenz zum dazugehörigen Fall der Bildgebungsstudie."
  * Beginn 0..1 http://hl7.org/fhir/StructureDefinition/dateTime "Beginn" "Datum und Zeitpunkt, an dem die Studie gestartet wurde (z.B. Zeitpunkt des Beginns der CT-Untersuchung)."
  * AnforderndeMaßnahme 0..* Reference(ServiceRequest) "Anfordernde Maßnahme" "Referenz auf die anfordernde Maßnahme dieser Bildgebungsstudie"
  * QuellePACS 0..* Reference(Endpoint) "Quelle zum PACS-Bild" "Referenz auf den Speicherort der Bildgebungsstudie im PACS"
  * AnzahlSerien 0..1 http://hl7.org/fhir/StructureDefinition/unsignedInt "Anzahl der Serien" "Anzahl der in der Bildgebungsstudie enthaltenen Serien, z.B. 5"
  * AnzahlInstanzen 0..1 http://hl7.org/fhir/StructureDefinition/unsignedInt "Anzahl der SOP Instanzen" "Anzahl der in der Bildgebungsstudie enthaltenen SOP Instanzen, z.B. 127"
  * Prozedur 0..1 Reference(Procedure) "Prozedur" "Referenz auf die dazugehörige medizinische Prozedur der Studie."
  * Bildgebungsgrund 0..* http://hl7.org/fhir/StructureDefinition/string "Bildgebungsgrund" "Grund, aus dem die Prozedur angefordert wurde"
  * Indikation 0..1 Reference(Condition or Observation) "Indikation" "Indikation der Bildgebungsstudie, d.h. der Grund, aus dem diese Bildgebung angefertigt wurde."
  * Studien-Beschreibung 0..1 http://hl7.org/fhir/StructureDefinition/string "Studien-Beschreibung" "Beschreibung der Bildgebungsstudie"
  * Serien 0..* BackboneElement "Serien" "Die Serien der DICOM-Studie"
    * Serien-UID 1..1 http://hl7.org/fhir/StructureDefinition/id "Serien-UID" "UID der DICOM-Serie"
    * Serien-Nummer 0..1 http://hl7.org/fhir/StructureDefinition/unsignedInt "Serien-Nummer" "Nummer der jeweiligen DICOM-Serie"
    * Modalität 1..1 http://hl7.org/fhir/StructureDefinition/Coding "Modalität" "Modalität der DICOM-Serie, z.B. 'MR' oder 'CR'"
    * Serien-Beschreibung 0..1 http://hl7.org/fhir/StructureDefinition/string "Serien-Beschreibung" "Beschreibung der jeweiligen Serie"
    * AnzahlInstanzen 0..1 http://hl7.org/fhir/StructureDefinition/unsignedInt "Anzhal der SOP Instanzen" "Anzahl der in der Serie enthaltenen SOP Instanzen, z.B. 28"
    * Körperregion 0..1 http://hl7.org/fhir/StructureDefinition/Coding "Körperregion" "Codierte Information über die untersuchte Körperregion der Serie"
    * Körperseite 0..1 http://hl7.org/fhir/StructureDefinition/Coding "Körperseite/Lateralität" "Information über die Körperseite der untersuchten Körperregion, z.B. linksseitig"
    * Beginn 0..1 http://hl7.org/fhir/StructureDefinition/dateTime "Beginn" "Datum und Zeitpunkt, an dem die Serie gestartet wurde (z.B. Zeitpunkt des Beginns der jeweiligen Serienaufnahme)."
    * Hersteller 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "Hersteller" "Hersteller der genutzten bildgebenden Modalität. "
    * Modell 0..1 http://hl7.org/fhir/StructureDefinition/string "Modell" "Das genutzte Modell des Herstellers der bildgebenden Modalität."
    * Kontrastmittelgabe 0..1 http://hl7.org/fhir/StructureDefinition/boolean "Kontrastmittelgabe" "Information darüber, ob bei der Serie Kontrastmittel genutzt wurde oder nicht"
    * Kontrastmitteldetails 0..* Reference(MedicationStatement) "Kontrastmitteldetails" "Details zur Kontrastmittelgabe über das MedicationStatement"
    * ModalitätDX 0..1 BackboneElement "Modalität DX" "Modalität klassisches Röntgen"
      * MaximaleRöntgenröhrenspannung 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Maximale Röntgenröhrenspannung" "Maximale Röntgenröhrenspannung in kV"
      * Expositionszeit 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Expositionszeit" "Expositionszeit in ms"
      * Exposition 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Exposition" "Exposition in MAs"
      * Röntgenröhrenstrom 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Röntgenröhrenstrom" "Röntgenröhrenstrom in mA"
    * ModalitätCR 0..1 BackboneElement "Modalität CR" "Modalität klassisches Röntgen"
      * MaximaleRöntgenröhrenspannung 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Maximale Röntgenröhrenspannung" "Maximale Röntgenröhrenspannung in kV"
      * Expositionszeit 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Expositionszeit" "Expositionszeit in ms"
      * Exposition 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Exposition" "Exposition in MAs"
      * Röntgenröhrenstrom 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Röntgenröhrenstrom" "Röntgenröhrenstrom in mA"
    * ModalitätMG 0..1 BackboneElement "Modalität MG" "Modalität Mammographie"
      * MaximaleRöntgenröhrenspannung 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Maximale Röntgenröhrenspannung" "Maximale Röntgenröhrenspannung in kV"
      * Expositionszeit 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Expositionszeit" "Expositionszeit in ms"
      * Exposition 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Exposition" "Exposition in MAs"
      * Röntgenröhrenstrom 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Röntgenröhrenstrom" "Röntgenröhrenstrom in mA"
    * ModalitätCT 0..1 BackboneElement "Modalität CT" "Modalität Computertomographie"
      * CTDIVolume 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "CTDIvolume" "CTDIvolume in mGy"
      * MaximaleRöntgenröhrenspannung 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Maximale Röntgenröhrenspannung" "Maximale Röntgenröhrenspannung in kV"
      * Expositionszeit 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Expositionszeit" "Expositionszeit in ms"
      * Exposition 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Exposition" "Exposition in MAs"
      * Röntgenröhrenstrom 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Röntgenröhrenstrom" "Röntgenröhrenstrom in mA"
    * ModalitätMR 0..1 BackboneElement "Modalität MR" "Modalität Kernspintomographie"
      * ScanningSequenz 1..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Scanning Sequenz" "Code der aktuellen Scanning Sequenz"
      * ScanningSequenzUntervariante 1..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "Scanning Sequenz Untervariante" "Code der aktuellen Scanning Sequenz Untervariante"
      * MagnetischeFeldstärke 1..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Magnetische Feldstärke" "Magnetische Feldstärke des Kernspins in T"
    * ModalitätPT 0..1 BackboneElement "Modalität PT" "Modalität PET-Scan"
      * Radiopharmakon 0..1 http://hl7.org/fhir/StructureDefinition/string "Radiopharmakon" "Genutztes Radiopharmakon"
      * Applikationsstartzeit 0..1 http://hl7.org/fhir/StructureDefinition/dateTime "Applikationsstartzeit" "Zeit des Beginn der Applikation des Radiopharmakons"
      * Reskaliserungstyp 0..1 http://hl7.org/fhir/StructureDefinition/string "Reskalierungstyp" "Abkürzung des Reskalierungstypen"
      * GesamteRadionukliddosis 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Gesamte Radionukliddosis" "Gesamte verabreichte Radionukliddosis in MBq"
      * Halbwertszeit 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Halbwertszeit" "Halbwertszeit des Radionuklids in s"
    * ModalitätNM 0..1 BackboneElement "Modalität NM" "Modalität Nuklearmedizin"
      * Radiopharmakon 0..1 http://hl7.org/fhir/StructureDefinition/string "Radiopharmakon" "Genutztes Radiopharmakon"
      * Applikationsstartzeit 0..1 http://hl7.org/fhir/StructureDefinition/dateTime "Applikationsstartzeit" "Zeit des Beginn der Applikation des Radiopharmakons"
      * Reskaliserungstyp 0..1 http://hl7.org/fhir/StructureDefinition/string "Reskalierungstyp" "Abkürzung des Reskalierungstypen"
      * GesamteRadionukliddosis 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Gesamte Radionukliddosis" "Gesamte verabreichte Radionukliddosis in MBq"
      * Halbwertszeit 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Halbwertszeit" "Halbwertszeit des Radionuklids in s"
    * Instanzen 0..* BackboneElement "Instanzen" "Alle Instanzen dieser DICOM-Serie."
      * SOP-Instanz 1..1 http://hl7.org/fhir/StructureDefinition/id "SOP-Instanz UID" "UID der jeweiligen SOP-Instanz"
      * SOP-Klasse 1..1 http://hl7.org/fhir/StructureDefinition/Coding "SOP-Klasse" "SOP-Klasse der jeweiligen SOP-Instanz"
      * Instanz-Nummer 0..1 http://hl7.org/fhir/StructureDefinition/unsignedInt "Instanz-Nummer" "Nummer der jeweiligen Instanz"
      * Bildtyp 0..1 http://hl7.org/fhir/StructureDefinition/string "Bildtyp" "Bildtyp der Instanz"
      * Schichtdicke 1..1 http://hl7.org/fhir/StructureDefinition/unsignedInt "Schichtdicke in mm" "Schichtdicke der SOP-Instanz in mm"
      * PixelabstandX 1..1 http://hl7.org/fhir/StructureDefinition/unsignedInt "Pixelabstand in x-Richtung in mm" "Pixelabstand in x-Richtung in mm"
      * PixelabstandY 1..1 http://hl7.org/fhir/StructureDefinition/unsignedInt "Pixelabstand in y-Richtung in mm" "Pixelabstand in y-Richtung in mm"


Mapping: Bildgebung-LogicalModel
Id: FHIR
Title: "Bildgebung LogicalModel FHIR Mapping"
Source: MII_LM_Bildgebung
* Empfehlung -> "CarePlan"
  * Status -> "CarePlan.status"
  * ArtEmpfehlung -> "CarePlan.intent"
  * FreitextEmpfehlung -> "CarePlan.description"
  * Zusatzinformation -> "CarePlan.supportingInfo"
* Befundbericht -> "DiagnosticReport"
  * AnforderndeMaßnahme -> "DiagnosticReport.basedOn"
  * Status -> "DiagnosticReport.status"
  * Person -> "DiagnosticReport.subject"
  * Fall -> "DiagnosticReport.encounter"
  * Zeitpunkt -> "DiagnosticReport.effectiveDateTime"
  * Periode -> "DiagnosticReport.effectivePeriod"
  * ZeitpunktErstellung -> "DiagnosticReport.issued"
  * Beobachtung -> "DiagnosticReport.result"
  * InterpretationBeobachtung -> "DiagnosticReport.conclusion"
  * StrukturierteInterpretation -> "DiagnosticReport.conclusionCode"
  * Zusatzinformation -> "DiagnosticReport.supportingInfo.reference"
  * Dokumentenanhang -> "DiagnosticReport.presentedForm"
  * Studienbezug -> "DiagnosticReport.study"
* SemistrukturiertesBefunddokument -> "Composition"
  * DatumUhrzeit -> "Composition.date"
  * Autor -> "Composition.author"
  * Befundbericht -> "Composition.subject"
  * Befundabschnitt -> "Composition.section"
    * Titel -> "Composition.section.title"
    * Art -> "Composition.section.code"
    * Text -> "Composition.section.text"
    * Eintrag -> "Composition.section.entry"
    * Unterabschnitt -> "Composition.section.section"
* GenerischeBeobachtung -> "Observation"
  * TeilEinerBefundungsprozedur -> "Observation.partOf"
  * Beobachtungstyp -> "Observation.code"
  * Status -> "Observation.status"
  * Beobachtungszeitpunkt -> "Observation.issued"
  * Beschreibung -> "Observation.value[x]"
  * Körperregion -> "Observation.bodySite"
  * Studienbezug -> "Obervation.derivedFrom"
  * WeitereBeobachtung -> "Observation.hasMember"
  * ErweiterteBeschreibung -> "Observation.component" //haben wir als Referenz abgebildet?
  * Bildnummer -> "Observation.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-bildnummer)"
  * Schichtposition -> "Observation.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-SOPInstanz)"
  * ErweiterteKörperstruktur -> "Observation.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-observation-imaging)" //Backport
* Anforderung -> "ServiceRequest"
  * ArtAnfrage -> "ServiceRequest.code"
  * Patientenbezug -> "ServiceRequest.subject"
  * Zusatzinformation -> "ServiceRequest.supportingInfo"
* Studie -> "ImagingStudy"
  * Status -> "ImagingStudy.status"
  * Modalitäten -> "ImagingStudy.modality"
  * Person -> "ImagingStudy.subject"
  * Fall -> "ImagingStudy.encounter"
  * Beginn -> "ImagingStudy.started"
  * AnforderndeMaßnahme -> "ImagingStudy.basedOn"
  * QuellePACS -> "ImagingStudy.endpoint"
  * AnzahlSerien -> "ImagingStudy.numberOfSeries"
  * AnzahlInstanzen -> "ImagingStudy.numberOfInstances"
  * Prozedur -> "ImagingStudy.procedureReference"
  * Indikation -> "ImagingStudy.reasonReference"
  * Studien-Beschreibung -> "ImagingStudy.description"
  * Bildgebungsgrund -> "ImagingStudy.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-bildgebungsgrund)"
  * Serien -> "ImagingStudy.series"
    * Serien-UID -> "ImagingStudy.series.uid"
    * Serien-Nummer -> "ImagingStudy.series.number"
    * Modalität -> "ImagingStudy.series.modality"
    * Serien-Beschreibung -> "ImagingStudy.series.description"
    * AnzahlInstanzen -> "ImagingStudy.series.numberOfInstances"
    * Körperregion -> "ImagingStudy.series.bodySite"
    * Körperseite -> "ImagingStudy.series.laterality"
    * Beginn -> "ImagingStudy.series.started"
    * Hersteller -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-geraet-hersteller)"
    * Modell -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-geraet-hersteller)"
    * Kontrastmittelgabe -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-kontrastmittel)"
    * Kontrastmitteldetails -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-kontrastmittel)"
    * ModalitätDX -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mg-cr-dx)"
      * MaximaleRöntgenröhrenspannung -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mg-cr-dx)"
      * Expositionszeit -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mg-cr-dx)"
      * Exposition -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mg-cr-dx)"
      * Röntgenröhrenstrom -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mg-cr-dx)"
    * ModalitätCR -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mg-cr-dx)"
      * MaximaleRöntgenröhrenspannung -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mg-cr-dx)"
      * Expositionszeit -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mg-cr-dx)"
      * Exposition -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mg-cr-dx)"
      * Röntgenröhrenstrom -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mg-cr-dx)"
    * ModalitätMG -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mg-cr-dx)"
      * MaximaleRöntgenröhrenspannung -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mg-cr-dx)"
      * Expositionszeit -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mg-cr-dx)"
      * Exposition -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mg-cr-dx)"
      * Röntgenröhrenstrom -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mg-cr-dx)"
    * ModalitätCT -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-ct)"
      * MaximaleRöntgenröhrenspannung -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-ct)"
      * Expositionszeit -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-ct)"
      * Exposition -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-ct)"
      * Röntgenröhrenstrom -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-ct)"
      * CTDIVolume -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-ct)"
    * ModalitätMR -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mr)"
      * ScanningSequenz -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mr)"
      * ScanningSequenzUntervariante -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mr)"
      * MagnetischeFeldstärke -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mr)"
    * ModalitätNM -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-pt-nm)"
      * Radiopharmakon -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-pt-nm)"
      * Applikationsstartzeit -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-pt-nm)"
      * Reskaliserungstyp -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-pt-nm)"
      * GesamteRadionukliddosis -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-pt-nm)"
      * Halbwertszeit -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-pt-nm)"
    * ModalitätPT -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-pt-nm)"
      * Radiopharmakon -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-pt-nm)"
      * Applikationsstartzeit -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-pt-nm)"
      * Reskaliserungstyp -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-pt-nm)"
      * GesamteRadionukliddosis -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-pt-nm)"
      * Halbwertszeit -> "ImagingStudy.series.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-pt-nm)"
    * Instanzen -> "ImagingStudy.series.instance"
      * SOP-Instanz -> "ImagingStudy.series.instance.uid"
      * SOP-Klasse -> "ImagingStudy.series.instance.sopClass"
      * Instanz-Nummer -> "ImagingStudy.series.instance.number"
      * Bildtyp -> "ImagingStudy.series.instance.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-instanz-serie)"
      * Schichtdicke -> "ImagingStudy.series.instance.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-instanz-serie)"
      * PixelabstandX -> "ImagingStudy.series.instance.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-instanz-serie)"
      * PixelabstandY -> "ImagingStudy.series.instance.extension(https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-instanz-serie)"

// Mapping: Bildgebung-LogicalModel-Profile
// Id: KDS-Profile
// Title: "Bildgebung LogicalModel KDS-Profile Mapping"
// Source: MII_LM_Bildgebung
// * Medikation -> "https://www.medizininformatik-initiative.de/fhir/core/modul-Bildgebung/StructureDefinition/Medication"
// * Medikationsliste -> "https://www.medizininformatik-initiative.de/fhir/core/modul-Bildgebung/StructureDefinition/Medikationsliste"
// * Medikationsverordnung -> "https://www.medizininformatik-initiative.de/fhir/core/modul-Bildgebung/StructureDefinition/MedicationRequest"
// * Medikationseintrag -> "https://www.medizininformatik-initiative.de/fhir/core/modul-Bildgebung/StructureDefinition/MedicationStatement"
// * Medikationsverabreichung -> "https://www.medizininformatik-initiative.de/fhir/core/modul-Bildgebung/StructureDefinition/MedicationAdministration"
